#pragma once
#define WM_USER_MSG (WM_USER + 1)
#define WM_USER_FRAME_CAPTURE_MSG (WM_USER + 2)
#define WM_USER_GET_VALID_IRIS_TEMPLATES_SUCC (WM_USER + 3)

//global macro definition
#define IRIS_IDENTITY_COMMON_BUFFER_LEN   512

#define CIRISIDENTITY_CAMERA_NO (1)

#define CIRISIDENTITY_PASS_COLOUR (RGB(50,205,50))